# /docker-compose.yml

# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./backend/.env
    depends_on:
      - judge-engine # Backend depends on the judge engine

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  
  judge-engine:
    build: ./judge-engine
    ports:
      - "8080:8080" # Expose the port for debugging if needed
    volumes:
      - ./judge-engine:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
