version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - judge-engine
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI = mongodb://mongo:27017/online-judge
      - JWT_SECRET = 14b8080df0af1814ee2c8190a89e309683d2d8748c60d3d5e549756f78826ea7
      - JUDGE_ENGINE_URL=http://judge-engine:5001
      - GEMINI_API_KEY=AIzaSyBIciKR4-8GzTyTZ46SNcbD_BApoGiBnXA

  judge-engine:
    build: ./judge-engine
    ports:
      - '5001:5001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./judge-engine:/app
      - /app/node_modules
    environment:
      - PORT=5001

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
